name: Dear world
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8efe6'
    - '#8f4141'
    - '#1d0000'
    - '#9f6e5f'
    - '#caa593'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 1
purpose: []
