name: Dear world
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080405'
    - '#8f4141'
    - '#7c8f96'
    - '#b7d0d5'
    - '#960013'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 1
purpose: []
